In [1]:
!pip install nptyping beartype --upgrade --force

  Obtaining dependency information for beartype from https://files.pythonhosted.org/packages/46/8a/a90fe78c73958340ed6b6ab128a10598ad5f0ff57537ad17f6ccd1ad830b/beartype-0.16.4-py3-none-any.whl.metadata
  Obtaining dependency information for numpy<2.0.0,>=1.20.0 from https://files.pythonhosted.org/packages/da/3c/3ff05c2855eee52588f489a4e607e4a61699a0742aa03ccf641c77f9eb0a/numpy-1.26.2-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.2 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 809.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
   ---- ----------------------------------- 92.2/819.1 kB 1.7 MB/s eta 0:00:01
   ----- ---------------------------------- 112.6/819.1 kB 2.2 MB/s eta 0:00:01
   ------- ------------------------------ 163.8/819.1 kB 984.6 kB/s eta 0:00:01
   ------------ --------------------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
numba 0.58.0 requires numpy<1.26,>=1.21, but you have numpy 1.26.2 which is incompatible.


## Scalar value

In [8]:
import numpy as np

a : np.ndarray = np.array(1000) # object to store

display(a) # prints
display(a.shape) # prints the shape of the object () = 0 -Denormalized
display(a.dtype) # prints the dtype of the object
display(type(a)) 
display(a.ndim) # prints the number of dimensions
display(a.size) # prints the size of the object
display(a.itemsize) # prints the itemsize of the object



array(1000)

()

dtype('int32')

numpy.ndarray

0

1

4

## Vector type

In [9]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4]) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object



' object [1 2 3 4]'

'objec shape (4,)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 1'

'Total items in Array : 4'

'4'

### Matrix

In [11]:
import numpy as np

data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]

a : np.ndarray = np.array(data) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object



' object [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]\n [11 12 13 14]]'

'objec shape (4, 4)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 2'

'Total items in Array : 16'

'4'

# Numpy with NDArray typing support

In [5]:
from nptyping import NDArray, Shape, UInt64
from typing import Any

data : NDArray[Shape["10"], Any] = np.arange(1,11)

print(data)
print(data + 5) # addition operation

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [6]:
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
d1 + 5

TypeError: can only concatenate list (not "int") to list

In [ ]:
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
[i+5 for i in d1 ]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [ ]:
%%time

data : NDArray[Shape["10"], Any] = np.arange(1,10000000)

data + 5 # addition operation

CPU times: user 16.1 ms, sys: 42.7 ms, total: 58.8 ms
Wall time: 93.3 ms


array([       6,        7,        8, ..., 10000002, 10000003, 10000004])

In [ ]:
%%time
data : list[int] = list(range(1,10000000))

[i + 5  for i in data]# addition operation

CPU times: user 215 ms, sys: 96.1 ms, total: 311 ms
Wall time: 361 ms


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


# numpy advanced operations vs list operations

In [ ]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5:11] = 1000 # normal python list
print(data)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [ ]:
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# Numpy 1d functions

In [ ]:
from nptyping import Bool

state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
#[1,      7,      8,     10]
#[True,  False, False, True]
#variable[[True,  False, False, True]]
#[1,10]
select : NDArray[Shape["10"],Bool]= np.array([True, False, False, True])

state_bank[select]




array([ 1, 10])

In [ ]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank % 2 == 0

array([False, False,  True,  True])

In [ ]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank[state_bank % 2 == 0]

array([ 8, 10])

In [ ]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])

ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1,100, 20)

display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([54, 48, 78, 12, 78, 26,  7,  7, 27, 83, 56, 36, 77, 18, 53, 19,  2,
       10, 16, 54])

In [ ]:
display(state_bank)
display(ubl_bank)

#        4item       search 20 items
np.in1d(state_bank,ubl_bank) # first variable items length returned

array([ 1,  7,  8, 10])

array([54, 48, 78, 12, 78, 26,  7,  7, 27, 83, 56, 36, 77, 18, 53, 19,  2,
       10, 16, 54])

array([False,  True, False,  True])

In [ ]:
display(state_bank)
display(ubl_bank)

#        4item       search 20 items
state_bank[np.in1d(state_bank,ubl_bank)] # first variable items length returned

array([ 1,  7,  8, 10])

array([54, 48, 78, 12, 78, 26,  7,  7, 27, 83, 56, 36, 77, 18, 53, 19,  2,
       10, 16, 54])

array([ 7, 10])

In [ ]:
np.intersect1d(state_bank,ubl_bank)

array([ 7, 10])

In [ ]:
x : NDArray[Shape["5"],Any] = np.array([1,3,4,5,7])
y : NDArray[Shape["5"],Any] = np.array([6,3,2,5,100])

display(x)
display(y)
np.where(x > y, x, y)

array([1, 3, 4, 5, 7])

array([  6,   3,   2,   5, 100])

array([  6,   3,   4,   5, 100])

# Create Numpy arrays

In [ ]:
a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([["A"],
                                                    ["B"]])
print(a)




[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [ ]:
a : NDArray[Shape["*, *"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([["A"],
                                                    ["B"]])
print(a)




[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [ ]:
np.who()

Name            Shape            Bytes            Type

_               5                40               int64
__              5                40               int64
___             2                16               int64
a               2 x 1            8                str32
_10             10               80               int64
_11             10               80               int64
_12             10               80               int64
_16             999999           7999992          int64
_19             9999999          79999992         int64
ndata           20               160              int64
state_bank      4                32               int64
ubl_bank        20               160              int64
select          4                4                bool
_29             2                16               int64
_30             4                4                bool
_32             2                16               int64
_35             3                3                

# Create any dimension array

In [ ]:
a : NDArray[Shape["Size"],Any] = np.arange(1,5)
print(a)
a : NDArray[Shape["Size"],Any] = np.arange(1,10)
print(a)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [ ]:
a : NDArray[Shape["Size, Size"],Any] = np.arange(3*3).reshape(3,3)
print(a)
a : NDArray[Shape["Size, Size"],Any] = np.arange(5*3).reshape(5,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print(a)
print('=======')
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [ ]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[::2,::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]]])

In [ ]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.asarray([1,2,3])

array([1, 2, 3])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [ ]:
np.ones_like(a)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[[0,-1],::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [ ]:
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)

print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax())
print(ndata.argmin)
print(ndata.mean())
print(ndata.std())
print(ndata.sum())
print(ndata.cumsum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
19
<built-in method argmin of numpy.ndarray object at 0x1452170f0>
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
